fastlane_version "2.61.0"

default_platform :ios

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(
        export_method: "app-store",
        export_options: {
          provisioningProfiles: {
            "com.manuelrauber.xcelerate" => "xcelerate app"
          }
        },
        workspace: "dist/mobile/platforms/ios/x-celerate.xcworkspace"
      )
    pilot
  end
end
